name: Playwright Tests

on:
  workflow_dispatch:  # Permite rodar manualmente via botão
    inputs:
      browser:
        description: "Escolher navegador"
        required: true
        default: "chromium"

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.2-jammy  # Imagem oficial Playwright

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright Tests
        run: |
          npx playwright install --with-deps
          npx playwright test \
            --project=${{ github.event.inputs.browser }} \
            --reporter=html \
            --workers=1 \
            --timeout=120000

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
