name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libnss3 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          libgbm-dev \
          libasound2 \
          libxshmfence1

    - name: Run Playwright tests with extended timeouts
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
        npx playwright test \
          --timeout=60000 \
          --retries=2 \
          --workers=2
      env:
        CI: true
        PLAYWRIGHT_TEST_TIMEOUT: 60000
        PLAYWRIGHT_TEST_RETRIES: 2

    - name: Generate HTML report
      if: always()
      run: npx playwright show-report

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 7