name: Run Playwright Tests E2E - TSFT

on:
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.54.2-jammy # versão compatível com seu projeto

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests (Chromium)
        run: |
          npx playwright test --project=chromium --reporter=html
          mv playwright-report playwright-report-chromium

      - name: Upload Chromium Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-chromium
          path: playwright-report-chromium/

      - name: Run Playwright tests (Firefox)
        run: |
          npx playwright test --project=firefox --reporter=html
          mv playwright-report playwright-report-firefox

      - name: Upload Firefox Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-firefox
          path: playwright-report-firefox/
