name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Escolher navegador"
        required: true
        default: "chromium"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: mcr.microsoft.com/playwright:v1.54.2-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (with retry)
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-mintimeout 1000
          npm config set fetch-retry-maxtimeout 60000
          npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ github.event.inputs.browser }}

      - name: Run Playwright Tests
        env:
          DEBUG: pw:api
        run: |
          npx playwright test \
            --project=${{ github.event.inputs.browser }} \
            --reporter=html \
            --workers=1

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
