name: Playwright Tests

on:
  workflow_dispatch: # botão manual
    inputs:
      browser:
        description: "Escolher navegador (chromium ou firefox)"
        required: true
        default: "chromium"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: mcr.microsoft.com/playwright:v1.54.2-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      # roda só no navegador escolhido
      - name: Run Playwright Tests
        run: |
          npx playwright test \
            --project=${{ github.event.inputs.browser }} \
            --reporter=list,html \
            --workers=2

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.event.inputs.browser }}
          path: playwright-report
