name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Create .env file with secrets
      run: |
        echo "SAFETECH_URL=${{ secrets.SAFETECH_URL }}" > .env
        echo "SAFETECH_USERNAME=${{ secrets.SAFETECH_USERNAME }}" >> .env
        echo "SAFETECH_PASSWORD=${{ secrets.SAFETECH_PASSWORD }}" >> .env
        echo "NODE_ENV=test" >> .env

    - name: Install dependencies
      run: npm ci

    - name: Install only Chromium browser
      run: npx playwright install chromium

    - name: Run Playwright tests
      run: npx playwright test --browser=chromium --timeout=60000
      env:
        CI: true

    - name: Upload Playwright report if exists
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

    - name: Upload test results if exist
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 7