on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Escolher navegador (chromium ou firefox)"
        required: true
        default: "chromium"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Aumenta o timeout geral
    container: mcr.microsoft.com/playwright:v1.54.2-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          npx playwright test \
            --project=${{ github.event.inputs.browser }} \
            --reporter=list,html \
            --workers=1 \
            --timeout=120000 # Timeout de 2 minutos por teste

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.event.inputs.browser }}
          path: playwright-report
