name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install only Chromium browser
      run: npx playwright install chromium

    - name: Install Xvfb for headful mode
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run Playwright tests only on Chromium
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
        npx playwright test --project=chromium
      env:
        CI: true

    - name: Generate HTML report
      if: always()
      run: npx playwright show-report

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7